rules = {"colors": ["blue", "yellow", "red", "black", "teal"],
         "amounts": [20, 20, 20, 20, 20],
         "factories": [5, 7, 9],
         "factorySize": 4,
         "minPlayers": 2,
         "boardType": 1,
         "tilesRequired": [1, 2, 3, 4, 5],
         "floor": [-1, -1, -2, -2, -2, -3, -3],
         "floorSize": 7,
         "rowScore": 2,
         "columnScore": 7,
         "colorScore": 10,
         "fps": 60,
         "patternSizes": [1, 2, 3, 4, 5],
         "centerSize": None,
         "boardSize": 6}

'''rules = {"colors": ["purple", "yellow", "red", "black", "teal"],
         "amounts": [20, 20, 20, 20, 20],
         "factories": [5, 7, 9],
         "factorySize": 4,
         "minPlayers": 2,
         "boardType": 1,
         "tilesRequired": [1, 2, 3, 4, 5],
         "floor": [-1, -1, -2, -2, -2, -3, -3],
         "floorSize": 7,
         "rowScore": 2,
         "columnScore": 7,
         "colorScore": 10,
         "fps": 60,
         "patternSizes": [1, 2, 3, 4, 5],
         "centerSize": None,
         "boardSize": 5}'''